# ===========================================================================
# modules/services/hypr-matugen.nix — matugen color sync for Hyprland
#
# Parallel to wallpaper-slideshow.nix (which handles COSMIC).
# For Hyprland, the trigger is set-wallpaper.sh (called from autostart.conf
# and any manual wallpaper change). That script calls `matugen image` directly
# after setting the wallpaper via swww.
#
# This module handles the static setup: packages, config.toml, seed files.
# ===========================================================================

{ config, pkgs, lib, ... }:

{
  # =========================================================================
  # Required packages
  # =========================================================================
  home.packages = with pkgs; [
    matugen     # Material You color generator
    git         # needed by matugenTemplates activation below
  ];

  # =========================================================================
  # matugen templates — clone from InioX/matugen-themes if not present
  # =========================================================================
  home.activation.matugenTemplates = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    TEMPLATES_DIR="$HOME/.config/matugen/templates"
    if [ ! -d "$TEMPLATES_DIR" ]; then
      echo "matugen: cloning templates from InioX/matugen-themes…"
      ${pkgs.git}/bin/git clone --depth=1 \
        https://github.com/InioX/matugen-themes.git \
        "$TEMPLATES_DIR" \
        && echo "matugen: templates ready at $TEMPLATES_DIR" \
        || echo "matugen: WARNING — template clone failed (no internet?). Run manually:"$'\n'"  git clone https://github.com/InioX/matugen-themes ~/.config/matugen/templates"
    fi
  '';

  # =========================================================================
  # Seed files — pre-create so apps don't fail before first matugen run
  # =========================================================================
  home.activation.hyprMatugenSeeds = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    # kitty colors
    KITTY_COLORS="$HOME/.config/kitty/colors.conf"
    if [ ! -f "$KITTY_COLORS" ]; then
      mkdir -p "$(dirname "$KITTY_COLORS")"
      touch "$KITTY_COLORS"
    fi

    # waybar colors — seed only if not already generated (preserve matugen output)
    WAYBAR_COLORS="$HOME/.config/waybar/colors.css"
    if [ ! -f "$WAYBAR_COLORS" ]; then
      mkdir -p "$(dirname "$WAYBAR_COLORS")"
      cat > "$WAYBAR_COLORS" << 'EOF'
/* Generated by matugen — do not edit manually.
 * Seed values: Catppuccin Mocha (replaced on first wallpaper set). */
:root, * {
    --primary:            #89b4fa;
    --on-primary:         #1e3a5f;
    --surface:            #1e1e2e;
    --on-surface:         #cdd6f4;
    --on-surface-variant: #a6adc8;
    --tertiary:           #fab387;
    --error:              #f38ba8;
    --outline-variant:    #45475a;
}
EOF
    fi
  '';

  # =========================================================================
  # matugen config.toml
  # =========================================================================
  home.file.".config/matugen/config.toml" = {
    force = true;
    text = ''
      # ===========================================================
      # matugen configuration — Hyprland
      # Generates Material You color themes from wallpaper images.
      # Triggered by ~/.config/hypr/scripts/set-wallpaper.sh.
      # Templates from: https://github.com/InioX/matugen-themes
      # ===========================================================

      [config]
      mode        = "dark"
      reload_apps = true

      [templates.starship]
      input_path  = "~/.config/matugen/templates/templates/starship-colors.toml"
      output_path = "~/.config/starship-colors.toml"

      [templates.gtk]
      input_path  = "~/.config/matugen/templates/templates/gtk-colors.css"
      output_path = "~/.config/gtk-4.0/colors.css"

      [templates.kitty]
      input_path  = "~/.config/matugen/templates/templates/kitty-colors.conf"
      output_path = "~/.config/kitty/colors.conf"
      post_hook   = "pkill -USR1 kitty || true"

      [templates.btop]
      input_path  = "~/.config/matugen/templates/templates/btop.theme"
      output_path = "~/.config/btop/themes/matugen.theme"
      post_hook   = "mkdir -p ~/.config/btop/themes && sed -i 's/^color_theme = .*/color_theme = \"matugen\"/' ~/.config/btop/btop.conf 2>/dev/null || true"

      [templates.zed]
      input_path  = "~/.config/matugen/templates/templates/zed-colors.json"
      output_path = "~/.config/zed/themes/matugen.json"

      [templates.waybar]
      input_path  = "~/nixos-config/dotfiles/hypr/waybar/colors.css.template"
      output_path = "~/.config/waybar/colors.css"
      post_hook   = "pkill -USR2 waybar || true"
    '';
  };
}
