# hyprlock-colors.conf — Matugen generated colors
$primary         = rgba(eab5eeff)
$on_primary      = rgba(48204fff)
$surface         = rgba(171217ff)
$on_surface      = rgba(eadfe6ff)
$on_surface_var  = rgba(d0c3ccff)
$surface_variant = rgba(4d444cff)
$tertiary        = rgba(f6b8afff)
$error           = rgba(ffb4abff)
$outline_var     = rgba(4d444cff)
