# hyprlock-colors.conf — Matugen generated colors
$primary         = rgba(80d4d8ff)
$on_primary      = rgba(003739ff)
$surface         = rgba(0e1415ff)
$on_surface      = rgba(dde4e4ff)
$on_surface_var  = rgba(bec8c9ff)
$surface_variant = rgba(3f4949ff)
$tertiary        = rgba(b5c7e9ff)
$error           = rgba(ffb4abff)
$outline_var     = rgba(3f4949ff)
