# hyprlock-colors.conf — Matugen generated colors
$primary         = rgba(feb877ff)
$on_primary      = rgba(4b2800ff)
$surface         = rgba(19120cff)
$on_surface      = rgba(efe0d5ff)
$on_surface_var  = rgba(d5c3b6ff)
$surface_variant = rgba(51443aff)
$tertiary        = rgba(c2cc99ff)
$error           = rgba(ffb4abff)
$outline_var     = rgba(51443aff)
