-- ===========================================================================
-- dotfiles/hypr/hyprland.lua — Hyprland entry point
--
-- Lua replaces hyprlang (.conf) as of Hyprland 0.55. This file requires
-- modules — one concern per file. hyprland.lua takes full priority over
-- hyprland.conf when both exist; the .conf file is never read.
--
-- Load order matters: colors must be required before appearance
-- (appearance.lua references the color globals defined there).
-- ===========================================================================

require("modules.environment")
require("modules.monitors")
require("modules.input")
pcall(require, "colors")       -- runtime-generated by matugen; may not exist on fresh install
require("modules.appearance")
require("modules.layout-hooks")
require("modules.windowrules")
require("modules.autostart")
require("modules.keybinds")

-- Shell-specific injections — written at HM activation by the active shell module.
--   shell-active.lua      = per-shell config overrides  (e.g. DMS colors/outputs)
--   shell-autostart.lua   = per-shell exec-once launch  (e.g. noctalia-shell)
-- Both files always exist (activation writes them, even if empty).
--
-- Component injections — written at HM activation when a modules/components/*
-- module is imported by the host. Each file is optional (safe_dofile skips
-- missing ones), so unused components leave no trace in the compositor state.
--   components/bar.lua           — waybar keybinds (layout cycle)
--   components/launcher.lua      — wofi/rofi keybinds + window rules
--   components/notifications.lua — swaync layer rules
local home = os.getenv("HOME")
local function safe_dofile(path)
    local f = io.open(path, "r")
    if f then f:close(); dofile(path) end
end
safe_dofile(home .. "/.config/hypr/shell-active.lua")
safe_dofile(home .. "/.config/hypr/shell-autostart.lua")
safe_dofile(home .. "/.config/hypr/components/bar.lua")
safe_dofile(home .. "/.config/hypr/components/launcher.lua")
safe_dofile(home .. "/.config/hypr/components/notifications.lua")

-- For Noctalia Color templates
require("noctalia").apply_theme()
