-- Auto-generated by DMS — do not edit directly.
-- Remove require("dms.colors") from shell-active.lua to override.

hl.config({
    general = {
        col = {
            active_border   = "rgb(a7c8ff)",
            inactive_border = "rgb(8c919c)",
        },
    },
    group = {
        col = {
            border_active          = "rgb(a7c8ff)",
            border_inactive        = "rgb(8c919c)",
            border_locked_active   = "rgb(ffb4ab)",
            border_locked_inactive = "rgb(8c919c)",
        },
        groupbar = {
            col = {
                active          = "rgb(a7c8ff)",
                inactive        = "rgb(8c919c)",
                locked_active   = "rgb(ffb4ab)",
                locked_inactive = "rgb(8c919c)",
            },
        },
    },
})
