-- Auto-generated by DMS — do not edit manually.

hl.env("HYPRCURSOR_THEME", "BreezeX-Light")
hl.env("XCURSOR_THEME",    "BreezeX-Light")
hl.env("HYPRCURSOR_SIZE",  "24")
hl.env("XCURSOR_SIZE",     "24")
