-- Auto-generated by DMS — do not edit manually.
-- DMS manages display configuration at runtime. This file is rewritten
-- by the DMS activation whenever display settings change.

hl.monitor({
    output   = "DP-3",
    mode     = "3440x1440@240.085",
    position = "0x0",
    scale    = "1",
    vrr      = 2,
    bitdepth = 10,
})
