require("options")
require("keymaps")

require("plugins.treesitter")
require("plugins.telescope")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.gitsigns")
require("plugins.obsidian")
require("plugins.neo-tree")
require("plugins.claudecode")
require("plugins.dashboard")
require("plugins.bufferline")
require("plugins.which-key")
require("plugins.lualine")
