# ===========================================================================
# modules/desktop-environments/kde.nix — KDE Plasma Desktop Environment
#
# KDE Plasma is a full-featured, highly customizable desktop environment.
# Your wife is already comfortable with it, so it's available as a fallback
# option on her machines if she ever wants to switch from COSMIC.
#
# To enable it on a host, simply import this module alongside cosmic.nix.
# Both can coexist — the user picks which one to log into at the login screen.
# ===========================================================================

{ config, pkgs, lib, ... }:

{
  imports = [
    ../greeters/sddm-catppuccin.nix  # SDDM + Catppuccin Mocha/Mauve login screen
  ];

  # =========================================================================
  # KDE Plasma 6
  #
  # plasma6 is the current generation of KDE.
  # enabling it automatically pulls in Qt6, KDE frameworks, and Plasma itself.
  # =========================================================================
  services.desktopManager.plasma6.enable = true;

  # =========================================================================
  # Qt platform theme
  #
  # NixOS defaults QT_QPA_PLATFORMTHEME=gtk2 for GTK integration. With KDE,
  # this causes kwin_wayland to crash on startup — GTK2's platform theme calls
  # gtk_init() which requires an X11 display, but kwin IS the display and
  # hasn't started one yet. Set it to "kde" so Qt uses KDE's native theme.
  # =========================================================================
  environment.sessionVariables.QT_QPA_PLATFORMTHEME = lib.mkForce "kde";

  # =========================================================================
  # Display Manager (Login Screen) — KDE-specific SDDM overrides
  #
  # sddm-catppuccin.nix (imported above) handles: enable, wayland.enable,
  # Catppuccin theme, PAM keyring, sddm user groups, and /run/user/175.
  #
  # KDE requires kwin_wayland as the greeter compositor instead of the
  # default weston. The CompositorCommand is forced here so it takes
  # precedence over the weston command generated by sddm-catppuccin.nix.
  #
  # When Plasma Login Manager matures and lands in nixpkgs, switching will
  # be a one-line change here.
  # =========================================================================

  # Clear QT_QPA_PLATFORMTHEME for the greeter process — it inherits the
  # system value (gtk2) which crashes sddm-greeter-qt6.
  services.displayManager.sddm.settings.General.GreeterEnvironment =
    "QT_WAYLAND_SHELL_INTEGRATION=layer-shell,QT_QPA_PLATFORMTHEME=";

  # SDDM strips its own environment before launching kwin_wayland, so env vars
  # set on display-manager.service never reach kwin. Use CompositorCommand.
  #
  # - KWIN_DRM_DEVICES: On Ryzen 7840U the NPU (amdxdna) claims DRM minor 0,
  #   pushing amdgpu to card1. kwin defaults to card0, finds nothing, exits 1.
  # - QT_QPA_PLATFORMTHEME=: Clear it for the greeter kwin too (same crash).
  services.displayManager.sddm.settings.Wayland.CompositorCommand = lib.mkForce
    "env KWIN_DRM_DEVICES=/dev/dri/card1 QT_QPA_PLATFORMTHEME= ${pkgs.kdePackages.kwin}/bin/kwin_wayland --no-global-shortcuts --no-kactivities --no-lockscreen --locale1";

  # =========================================================================
  # XDG Portal for KDE
  #
  # Same portal system as COSMIC but using KDE's implementation.
  # Handles file pickers, screen sharing etc for KDE apps.
  # =========================================================================
  xdg.portal = {
    enable = true;
    extraPortals = [ pkgs.kdePackages.xdg-desktop-portal-kde ];
  };

  # =========================================================================
  # KDE core packages
  #
  # Plasma comes with a lot built in, but these are commonly needed extras.
  # Keep this minimal — user preference apps belong in home.nix.
  # =========================================================================
  environment.systemPackages = with pkgs; [
    kdePackages.kate          # KDE text editor
    kdePackages.dolphin       # KDE file manager
    kdePackages.ark           # Archive manager (zip, tar, etc)
    kdePackages.kcalc         # Calculator
    kdePackages.okular        # Document viewer (PDF, etc)
    kdePackages.gwenview      # Image viewer
    kdePackages.plasma-browser-integration  # Browser integration for KDE
    kdePackages.qtstyleplugin-kvantum  # Kvantum theme engine for Qt apps
    kdePackages.sddm-kcm               # SDDM config in System Settings → Colors & Themes
    ant-dark-kde                  # Ant-Dark KDE theme (Aurorae, Plasma, color scheme, Kvantum)
    breeze-chameleon-dark-icons   # Breeze Chameleon Dark icon theme (adaptive folder colors)
    darkly                    # Window decoration + application style (fork of Lightly)
    kara                      # Desktop/workspace pager widget
    plasmusic-toolbar         # Now-playing + playback controls widget (Claudio Catterina)
    # shutdown_or_switch: not yet in nixpkgs — install via KDE Store (Kai Uwe Broulik / Davide Sandona)
  ];

  # =========================================================================
  # TODO: plasma-foreground-booster (kdePackages.kcgroups)
  #
  # Once kcgroups lands in nixpkgs, add it here. It's the KDE-specific piece
  # that signals the focused window to dmemcg-booster (already enabled via
  # gaming.nix). Without it the daemon runs but has no focus awareness.
  # =========================================================================

}
