-- ============================================================
-- Colorscheme — matugen (Material You, generated from wallpaper)
--
-- The file ~/.config/nvim/colors/matugen.lua is generated by
-- matugen on every wallpaper change. If it doesn't exist yet,
-- neovim falls back to the built-in "habamax" dark theme.
-- ============================================================

local colors_file = vim.fn.expand("~/.config/nvim/colors/matugen.lua")

if vim.fn.filereadable(colors_file) == 1 then
  local ok, err = pcall(vim.cmd, "colorscheme matugen")
  if not ok then
    vim.notify("matugen colorscheme failed: " .. err, vim.log.levels.WARN)
    vim.cmd("colorscheme habamax")
  end
else
  -- Colors not yet generated — run the wallpaper slideshow to generate them
  vim.cmd("colorscheme habamax")
  vim.notify(
    "matugen colors not found. Run your wallpaper slideshow to generate them.",
    vim.log.levels.INFO
  )
end
