-- ===========================================================================
-- modules/appearance.lua — Visual style: gaps, borders, blur, animations
--
-- Colors (primary, tertiary, outline_variant, …) are globals from colors.lua,
-- runtime-generated by matugen. If colors.lua doesn't exist yet (fresh install),
-- the col.* block is skipped and Hyprland uses its built-in defaults until
-- matugen runs (10 s after session start via the matugen systemd timer).
-- ===========================================================================

-- ── Layout + borders ─────────────────────────────────────────────────────────
hl.config({
    general = {
        gaps_in          = 5,
        gaps_out         = 10,
        border_size      = 2,
        layout           = "scrolling",
        resize_on_border = true,    -- Drag window edges to resize
    },
})

-- Apply matugen colors only when colors.lua has been loaded
-- (primary / tertiary / outline_variant are globals set by colors.lua)
if primary then
    hl.config({
        general = {
            col = {
                -- Two-color gradient border at 45° on active windows
                active_border   = { colors = { primary, tertiary }, angle = 45 },
                inactive_border = outline_variant,
            },
        },
    })
end

-- ── Decoration ───────────────────────────────────────────────────────────────
hl.config({
    decoration = {
        rounding = 10,

        -- Blur — frosted glass effect on transparent windows (kitty, waybar, wofi)
        blur = {
            enabled           = true,
            size              = 8,
            passes            = 2,
            new_optimizations = true,
            vibrancy          = 0.17,
        },

        -- Shadows — subtle depth without being heavy
        shadow = {
            enabled      = true,
            range        = 12,
            render_power = 3,
            color        = "rgba(00000055)",
        },
    },
})

-- ── Animation curves ─────────────────────────────────────────────────────────
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutSine",  { type = "bezier", points = { {0.37, 0},    {0.63, 1}    } })
hl.curve("easeOutBack",    { type = "bezier", points = { {0.34, 1.56}, {0.64, 1}    } })   -- Slight overshoot
hl.curve("easeInBack",     { type = "bezier", points = { {0.36, 0},    {0.66, -0.56} } })   -- Pulls inward before closing
hl.curve("linear",         { type = "bezier", points = { {0,    0},    {1,    1}    } })

-- ── Animations ───────────────────────────────────────────────────────────────
hl.config({ animations = { enabled = true } })

-- Windows
hl.animation({ leaf = "windows",     enabled = true, speed = 5,  bezier = "easeOutBack",   style = "popin"    })
hl.animation({ leaf = "windowsOut",  enabled = true, speed = 4,  bezier = "easeInBack",    style = "popin"    })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4,  bezier = "easeOutQuint"                      })

-- Borders
hl.animation({ leaf = "border",      enabled = true, speed = 6,  bezier = "default"                           })
hl.animation({ leaf = "borderangle", enabled = true, speed = 60, bezier = "linear",        style = "loop"     })   -- Rotating gradient

-- Fades
hl.animation({ leaf = "fade",        enabled = true, speed = 4,  bezier = "easeInOutSine"                     })
hl.animation({ leaf = "fadeOut",     enabled = true, speed = 4,  bezier = "easeInOutSine"                     })

-- Workspaces
hl.animation({ leaf = "workspaces",  enabled = true, speed = 5,  bezier = "easeOutBack",   style = "slide"         })

-- ── Layout options ────────────────────────────────────────────────────────────
hl.config({
    dwindle = {
        preserve_split  = true,   -- Split direction is remembered per-split
        smart_split     = false,
        smart_resizing  = true,
    },
    master = {
        new_status = "master",
    },
    scrolling = {
        fullscreen_on_one_column = false,
        column_width             = 0.67,   -- 67%: default for new columns; layout-hooks.lua
                                           -- dynamically adjusts to 50% when 2+ windows exist.
        direction                = "right",
    },
})

-- ── Workspace rules ──────────────────────────────────────────────────────────
-- Persist workspaces 1–9 so they always exist (Noctalia displays all persistent
-- workspaces even when empty). No layout pin — use Super+backslash to cycle.
for i = 1, 9 do
    hl.workspace_rule({
        workspace  = tostring(i),
        persistent = true,
        default    = (i == 1),   -- workspace 1 is the landing workspace on each monitor
    })
end

-- ── Render + misc ─────────────────────────────────────────────────────────────
hl.config({
    render = {
        direct_scanout = 0,   -- Disabled — causes flickering when entering/leaving fullscreen
    },
    misc = {
        force_default_wallpaper  = 0,
        disable_hyprland_logo    = true,
        disable_splash_rendering = true,
        mouse_move_enables_dpms  = true,
        key_press_enables_dpms   = true,
        animate_manual_resizes   = true,
        vrr                      = 2,   -- Fullscreen-only VRR
    },
})
