# ===========================================================================
# modules/compositors/umbriel/noctalia-bridge/default.nix
#
# Workaround for an upstream noctalia-dev schema mismatch, not our bug:
# Noctalia's own umbriel theming writes ~/.config/umbriel/noctalia.toml
# using appearance.border_focused / appearance.outer_border_color /
# overview.background_tint etc — but Umbriel 0.1.0's real schema (confirmed
# from its own example config) is colors.border.focused / colors.border.outer
# / colors.overview.background_tint. Umbriel logs 8 "unknown key" warnings
# and silently ignores them — the main [colors] section (background/text/
# accent) matches and works fine; only border/overview colors are affected.
#
# Watches noctalia.toml (Noctalia's fully-owned, wholesale-rewritten output —
# never edited in place, unlike kitty.conf) and remaps the mismatched keys
# into a separate noctalia-fixed.toml, which
# modules/compositors/umbriel/default.nix includes instead of noctalia.toml
# directly. Same path-unit-watch pattern as the matugen module.
#
# Delete this whole directory (and its import + the include.files entry)
# once noctalia-dev reconciles the two projects' schemas upstream.
# ===========================================================================

{ pkgs, ... }:

let
  bridge = pkgs.writeShellScript "noctalia-umbriel-bridge" ''
    exec ${pkgs.python3}/bin/python3 - <<'PYEOF'
    import pathlib
    import tomllib

    home = pathlib.Path.home()
    src = home / ".config/umbriel/noctalia.toml"
    dst = home / ".config/umbriel/noctalia-fixed.toml"

    if not src.exists():
        raise SystemExit(0)

    with src.open("rb") as f:
        data = tomllib.load(f)

    colors = dict(data.get("colors", {}))
    appearance = data.get("appearance", {})
    overview = data.get("overview", {})

    # appearance.* keys that just move into [colors] under a new name
    for src_key, dst_key in {
        "insert_hint_color": "insert_hint",
        "backdrop_color": "backdrop",
    }.items():
        if src_key in appearance:
            colors[dst_key] = appearance[src_key]

    # appearance.*border* keys that move into [colors.border]
    border = {}
    for src_key, dst_key in {
        "border_focused": "focused",
        "border_unfocused": "unfocused",
        "scratchpad_border_focused": "scratchpad_focused",
        "scratchpad_border_unfocused": "scratchpad_unfocused",
        "outer_border_color": "outer",
    }.items():
        if src_key in appearance:
            border[dst_key] = appearance[src_key]

    out_overview = {
        k: v for k, v in overview.items() if k in ("background_tint", "workspace_background", "badge")
    }

    lines = [
        "# Auto-generated by noctalia-umbriel-bridge from noctalia.toml.",
        "# Do not edit manually — regenerated on every wallpaper change.",
        "# Remaps Noctalia's appearance.*/overview.* keys to Umbriel's real",
        "# colors.border.*/colors.overview.* schema (upstream schema mismatch",
        "# between noctalia-dev's own Noctalia and Umbriel projects).",
        "",
        "[colors]",
        *(f'{k} = "{v}"' for k, v in colors.items()),
        "",
    ]
    if border:
        lines += ["[colors.border]", *(f'{k} = "{v}"' for k, v in border.items()), ""]
    if out_overview:
        lines += ["[colors.overview]", *(f'{k} = "{v}"' for k, v in out_overview.items()), ""]

    dst.write_text("\n".join(lines))
    PYEOF
  '';
in

{
  systemd.user.services.noctaliaUmbrielBridge = {
    Unit.Description = "Remap Noctalia's umbriel theme keys to Umbriel's real schema";
    Service = {
      Type = "oneshot";
      ExecStart = "${bridge}";
    };
  };

  systemd.user.paths.noctaliaUmbrielBridge = {
    Unit.Description = "Watch noctalia.toml for Noctalia's umbriel theme writes";
    Path.PathChanged = "%h/.config/umbriel/noctalia.toml";
    Install.WantedBy = [ "graphical-session.target" ];
  };

  # Fires once shortly after session start too, in case noctalia.toml
  # already exists from a previous session (path units only fire on change).
  systemd.user.timers.noctaliaUmbrielBridge = {
    Unit.Description = "Run the umbriel theme key remap once on session start";
    Timer.OnActiveSec = "15s";
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
