# ===========================================================================
# modules/compositors/umbriel/noctalia-bridge/default.nix
#
# Workaround for an upstream noctalia-dev schema mismatch, not our bug:
# Noctalia's own umbriel theming writes ~/.config/umbriel/noctalia.toml
# using appearance.border_focused / appearance.outer_border_color /
# overview.background_tint etc — but Umbriel 0.1.0's real schema (confirmed
# from its own example config) is colors.border.focused / colors.border.outer
# / colors.overview.background_tint. Umbriel logs 8 "unknown key" warnings
# and silently ignores them — the main [colors] section (background/text/
# accent) matches and works fine; only border/overview colors are affected.
#
# Watches noctalia.toml (Noctalia's fully-owned, wholesale-rewritten output —
# never edited in place, unlike kitty.conf) and remaps the mismatched keys
# into a separate noctalia-fixed.toml, which
# modules/compositors/umbriel/default.nix includes instead of noctalia.toml
# directly. Same path-unit-watch pattern as the matugen module.
#
# Delete this whole directory (and its import + the include.files entry)
# once noctalia-dev reconciles the two projects' schemas upstream.
#
# Second problem, discovered live: Noctalia's own umbriel apply.sh also
# tries to inject "noctalia.toml" into config.toml's [include] list on
# every wallpaper change — previously a silent no-op against the old
# Nix-store-symlinked config.toml, but now that config.toml is a real
# writable file (dotfiles/umbriel/, live-symlinked), that write succeeds.
# Since it appends last and "later files override earlier ones" in
# Umbriel's [include] rule, the raw (wrong-schema) noctalia.toml wins
# over our own noctalia-fixed.toml include every time, bringing the 8
# unknown-key warnings straight back. configGuard below watches
# config.toml itself and strips that injection right back out — reacts
# to Noctalia's own write directly rather than guessing at ordering
# relative to noctalia.toml's own write. Idempotent: once removed, the
# next run finds nothing to fix and doesn't rewrite, so this can't loop.
# ===========================================================================

{ pkgs, ... }:

let
  configGuard = pkgs.writeShellScript "umbriel-config-guard" ''
    exec ${pkgs.python3}/bin/python3 - <<'PYEOF'
    import pathlib
    import re

    cfg = pathlib.Path.home() / ".config/umbriel/config.toml"
    if not cfg.exists():
        raise SystemExit(0)

    text = cfg.read_text()

    def strip_noctalia_toml(match):
        items = re.findall(r'"[^"]*"', match.group(2))
        items = [i for i in items if i != '"noctalia.toml"']
        return match.group(1) + ", ".join(items) + match.group(3)

    new_text = re.sub(
        r'(\[include\]\s*\nfiles\s*=\s*\[)([^\]]*)(\])',
        strip_noctalia_toml,
        text,
    )

    if new_text != text:
        cfg.write_text(new_text)
    PYEOF
  '';

  bridge = pkgs.writeShellScript "noctalia-umbriel-bridge" ''
    exec ${pkgs.python3}/bin/python3 - <<'PYEOF'
    import pathlib
    import tomllib

    home = pathlib.Path.home()
    src = home / ".config/umbriel/noctalia.toml"
    dst = home / ".config/umbriel/noctalia-fixed.toml"

    if not src.exists():
        raise SystemExit(0)

    with src.open("rb") as f:
        data = tomllib.load(f)

    colors = dict(data.get("colors", {}))
    appearance = data.get("appearance", {})
    overview = data.get("overview", {})

    # appearance.* keys that just move into [colors] under a new name
    for src_key, dst_key in {
        "insert_hint_color": "insert_hint",
        "backdrop_color": "backdrop",
    }.items():
        if src_key in appearance:
            colors[dst_key] = appearance[src_key]

    # appearance.*border* keys that move into [colors.border]
    border = {}
    for src_key, dst_key in {
        "border_focused": "focused",
        "border_unfocused": "unfocused",
        "scratchpad_border_focused": "scratchpad_focused",
        "scratchpad_border_unfocused": "scratchpad_unfocused",
        "outer_border_color": "outer",
    }.items():
        if src_key in appearance:
            border[dst_key] = appearance[src_key]

    out_overview = {
        k: v for k, v in overview.items() if k in ("background_tint", "workspace_background", "badge")
    }

    lines = [
        "# Auto-generated by noctalia-umbriel-bridge from noctalia.toml.",
        "# Do not edit manually — regenerated on every wallpaper change.",
        "# Remaps Noctalia's appearance.*/overview.* keys to Umbriel's real",
        "# colors.border.*/colors.overview.* schema (upstream schema mismatch",
        "# between noctalia-dev's own Noctalia and Umbriel projects).",
        "",
        "[colors]",
        *(f'{k} = "{v}"' for k, v in colors.items()),
        "",
    ]
    if border:
        lines += ["[colors.border]", *(f'{k} = "{v}"' for k, v in border.items()), ""]
    if out_overview:
        lines += ["[colors.overview]", *(f'{k} = "{v}"' for k, v in out_overview.items()), ""]

    dst.write_text("\n".join(lines))
    PYEOF
  '';
in

{
  systemd.user.services.noctaliaUmbrielBridge = {
    Unit.Description = "Remap Noctalia's umbriel theme keys to Umbriel's real schema";
    Service = {
      Type = "oneshot";
      ExecStart = "${bridge}";
    };
  };

  systemd.user.paths.noctaliaUmbrielBridge = {
    Unit.Description = "Watch noctalia.toml for Noctalia's umbriel theme writes";
    Path.PathChanged = "%h/.config/umbriel/noctalia.toml";
    Install.WantedBy = [ "graphical-session.target" ];
  };

  # Fires once shortly after session start too, in case noctalia.toml
  # already exists from a previous session (path units only fire on change).
  systemd.user.timers.noctaliaUmbrielBridge = {
    Unit.Description = "Run the umbriel theme key remap once on session start";
    Timer.OnActiveSec = "15s";
    Install.WantedBy = [ "graphical-session.target" ];
  };

  systemd.user.services.umbrielConfigGuard = {
    Unit.Description = "Strip Noctalia's noctalia.toml include injection from umbriel config.toml";
    Service = {
      Type = "oneshot";
      ExecStart = "${configGuard}";
    };
  };

  systemd.user.paths.umbrielConfigGuard = {
    Unit.Description = "Watch umbriel config.toml for Noctalia's own include injection";
    Path.PathChanged = "%h/.config/umbriel/config.toml";
    Install.WantedBy = [ "graphical-session.target" ];
  };
}
