# ===========================================================================
# modules/system/graphical/firefox/default.nix — Firefox
#
# Installs Firefox. By default also deploys the "de-slop" managed policy
# (../../../../dotfiles/firefox/policies.json) to /etc/firefox/policies/
# policies.json — telemetry/AI/password-manager off, uBlock Origin and
# Proton Pass force-installed, uBlock preloaded with a hardened filter list
# plus the yt-shorts hider (github.com/gijsdev/ublock-hide-yt-shorts). Set
# programs.firefox.deSlop.enable = false; on a host to opt out.
#
# The uBlock filterLists/externalLists set is duplicated in
# dotfiles/chromium/policies.json (different browser, same extension) —
# keep them in sync by hand when editing either.
# Imported per-host via the host imports list.
# ===========================================================================

{ config, lib, ... }:

let
  cfg = config.programs.firefox;
in

{
  options.programs.firefox.deSlop.enable = lib.mkOption {
    type = lib.types.bool;
    default = true;
    description = "Deploy the de-slop managed policy (dotfiles/firefox/policies.json).";
  };

  config = lib.mkMerge [
    { programs.firefox.enable = true; }

    (lib.mkIf cfg.deSlop.enable {
      programs.firefox.policies =
        (builtins.fromJSON (builtins.readFile ../../../../dotfiles/firefox/policies.json)).policies;
    })

    {
      # userChrome.css + pywalfox native-messaging manifest — applies to
      # every user on every host that imports this module.
      home-manager.sharedModules = [
        ({ lib, pkgs, ... }: {
          # pywalfox's native-messaging-host manifest — a fixed top-level
          # path (~/.mozilla/native-messaging-hosts/), independent of
          # profile existence, unlike userChrome.css below. Content
          # hardcoded to match the package's own install-time template
          # (pywalfox/assets/manifest.json, "<path>" substituted) — same
          # convention as dotfiles/firefox/policies.json, a static
          # hand-maintained file rather than something derived.
          home.file.".mozilla/native-messaging-hosts/pywalfox.json" = {
            force = true; # overwrite the manually-created file from before this was declarative
            text = builtins.toJSON {
              name = "pywalfox";
              description = "Automatically theme your browser using the colors generated by Pywal";
              path = "/run/current-system/sw/bin/pywalfox";
              type = "stdio";
              allowed_extensions = [ "pywalfox@frewacom.org" ];
            };
          };

          # userChrome.css — profile dir has a random suffix (e.g.
          # yhtttubw.default under NixOS's ~/.config/mozilla/firefox/, not
          # the traditional ~/.mozilla/firefox/), so it can't be a static
          # home.file path. A plain activation script would silently no-op
          # on a host where Firefox has never been launched yet (no
          # profile dir to find) — this path unit fires immediately if the
          # profile already exists, and automatically once Firefox creates
          # it on first launch, so no second rebuild is ever needed.
          systemd.user.services.firefoxUserChrome = {
            Unit = {
              Description = "Symlink userChrome.css into the Firefox profile";
              # PathExistsGlob (below) re-fires as long as the glob keeps
              # matching, not just once on the transition — which it will,
              # forever, once a profile exists. Each run is a cheap no-op
              # mkdir+ln, but without this it hits systemd's default
              # start-rate-limit within seconds and the unit ends up
              # "failed" even though the actual work already succeeded.
              StartLimitIntervalSec = 0;
            };
            Service = {
              Type = "oneshot";
              Environment = [
                "SHELL=/bin/sh"
                "PATH=/run/current-system/sw/bin:/etc/profiles/per-user/%u/bin:/usr/bin:/bin"
              ];
              ExecStart = pkgs.writeShellScript "firefox-userchrome" ''
                _profile=$(ls -d "$HOME/.config/mozilla/firefox/"*.default* 2>/dev/null | head -1)
                if [ -n "$_profile" ]; then
                  mkdir -p "$_profile/chrome"
                  ln -sf "$HOME/nixos-config/dotfiles/firefox/userChrome.css" "$_profile/chrome/userChrome.css"
                fi
              '';
            };
          };

          systemd.user.paths.firefoxUserChrome = {
            Unit.Description = "Watch for the Firefox profile directory to exist";
            Path.PathExistsGlob = "%h/.config/mozilla/firefox/*.default*";
            Install.WantedBy = [ "graphical-session.target" ];
          };
        })
      ];
    }
  ];

  # gfx.color_management.hdr / .force_enabled are left unset: they enable
  # Wayland HDR video, but Gecko renders it with a blown-out red tint — a
  # known upstream bug (bugzilla 1642854 and related Wayland
  # color-management reports), not fixable from config. Revisit once
  # Mozilla ships a fix; broken red-tinted HDR is worse than normal SDR.
}
