-- ===========================================================================
-- Neovim matugen colorscheme template
-- Generated by matugen on every wallpaper change.
-- Output: ~/.config/nvim/colors/matugen.lua
--
-- DO NOT EDIT the output file — it will be overwritten on the next
-- wallpaper change. Edit this template instead.
--
-- Template syntax: {{colors.<role>.<variant>.hex}}
-- Roles: primary, secondary, tertiary, error, surface, surface_dim,
--        surface_bright, surface_container, surface_container_high,
--        surface_container_low, on_surface, on_surface_variant,
--        on_primary, on_secondary, outline, outline_variant
-- ===========================================================================

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then vim.cmd("syntax reset") end
vim.g.colors_name = "matugen"

local c = {
  -- Backgrounds
  bg          = "#{{colors.surface.default.hex}}",
  bg_dim      = "#{{colors.surface_dim.default.hex}}",
  bg_bright   = "#{{colors.surface_bright.default.hex}}",

  -- Containers (panels, popups, sidebars)
  container   = "#{{colors.surface_container.default.hex}}",
  cont_high   = "#{{colors.surface_container_high.default.hex}}",
  cont_low    = "#{{colors.surface_container_low.default.hex}}",

  -- Foreground / text
  fg          = "#{{colors.on_surface.default.hex}}",
  fg_muted    = "#{{colors.on_surface_variant.default.hex}}",

  -- Primary (keywords, highlights, active elements)
  primary     = "#{{colors.primary.default.hex}}",
  on_primary  = "#{{colors.on_primary.default.hex}}",

  -- Secondary (strings, types)
  secondary   = "#{{colors.secondary.default.hex}}",
  on_sec      = "#{{colors.on_secondary.default.hex}}",

  -- Tertiary (functions, numbers)
  tertiary    = "#{{colors.tertiary.default.hex}}",

  -- Error
  error       = "#{{colors.error.default.hex}}",
  on_error    = "#{{colors.on_error.default.hex}}",

  -- Borders / separators
  outline     = "#{{colors.outline.default.hex}}",
  outline_v   = "#{{colors.outline_variant.default.hex}}",
}

local function hi(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- ===========================================================================
-- Editor base
-- ===========================================================================
hi("Normal",        { fg = c.fg,       bg = "NONE" })       -- transparent bg blends with terminal
hi("NormalFloat",   { fg = c.fg,       bg = c.container })
hi("NormalNC",      { fg = c.fg_muted, bg = "NONE" })
hi("EndOfBuffer",   { fg = c.outline_v })

hi("LineNr",        { fg = c.outline })
hi("CursorLine",    { bg = c.cont_low })
hi("CursorLineNr",  { fg = c.primary, bold = true })
hi("CursorColumn",  { bg = c.cont_low })
hi("SignColumn",    { bg = "NONE" })
hi("ColorColumn",   { bg = c.cont_low })

hi("Folded",        { fg = c.fg_muted, bg = c.container })
hi("FoldColumn",    { fg = c.outline, bg = "NONE" })

hi("VertSplit",     { fg = c.outline_v })
hi("WinSeparator",  { fg = c.outline_v })

hi("NonText",       { fg = c.outline })
hi("SpecialKey",    { fg = c.outline })
hi("Whitespace",    { fg = c.outline_v })
hi("Conceal",       { fg = c.fg_muted })

-- ===========================================================================
-- Popup / completion menu
-- ===========================================================================
hi("Pmenu",         { fg = c.fg,        bg = c.container })
hi("PmenuSel",      { fg = c.on_primary, bg = c.primary, bold = true })
hi("PmenuSbar",     { bg = c.cont_high })
hi("PmenuThumb",    { bg = c.primary })
hi("PmenuBorder",   { fg = c.outline, bg = c.container })

-- ===========================================================================
-- Search & selection
-- ===========================================================================
hi("Search",        { fg = c.bg,     bg = c.secondary })
hi("IncSearch",     { fg = c.bg,     bg = c.primary, bold = true })
hi("CurSearch",     { fg = c.bg,     bg = c.primary, bold = true })
hi("Visual",        { bg = c.cont_high })
hi("VisualNOS",     { bg = c.cont_high })
hi("MatchParen",    { fg = c.primary, bold = true, underline = true })

-- ===========================================================================
-- Status / tab line
-- ===========================================================================
hi("StatusLine",    { fg = c.fg,       bg = c.container })
hi("StatusLineNC",  { fg = c.fg_muted, bg = c.cont_low })
hi("TabLine",       { fg = c.fg_muted, bg = c.cont_low })
hi("TabLineFill",   { bg = c.cont_low })
hi("TabLineSel",    { fg = c.primary,  bg = c.container, bold = true })
hi("WinBar",        { fg = c.fg_muted, bg = "NONE" })
hi("WinBarNC",      { fg = c.outline,  bg = "NONE" })

-- ===========================================================================
-- Messages / cmd
-- ===========================================================================
hi("ModeMsg",       { fg = c.primary,   bold = true })
hi("MoreMsg",       { fg = c.secondary, bold = true })
hi("WarningMsg",    { fg = c.tertiary })
hi("ErrorMsg",      { fg = c.error })
hi("Question",      { fg = c.secondary })

-- ===========================================================================
-- Diagnostics
-- ===========================================================================
hi("DiagnosticError",            { fg = c.error })
hi("DiagnosticWarn",             { fg = c.tertiary })
hi("DiagnosticInfo",             { fg = c.secondary })
hi("DiagnosticHint",             { fg = c.primary })
hi("DiagnosticOk",               { fg = c.secondary })
hi("DiagnosticUnderlineError",   { underline = true, sp = c.error })
hi("DiagnosticUnderlineWarn",    { underline = true, sp = c.tertiary })
hi("DiagnosticUnderlineInfo",    { underline = true, sp = c.secondary })
hi("DiagnosticUnderlineHint",    { underline = true, sp = c.primary })
hi("DiagnosticVirtualTextError", { fg = c.error,     italic = true })
hi("DiagnosticVirtualTextWarn",  { fg = c.tertiary,  italic = true })
hi("DiagnosticVirtualTextInfo",  { fg = c.secondary, italic = true })
hi("DiagnosticVirtualTextHint",  { fg = c.primary,   italic = true })
hi("DiagnosticSignError",        { fg = c.error })
hi("DiagnosticSignWarn",         { fg = c.tertiary })
hi("DiagnosticSignInfo",         { fg = c.secondary })
hi("DiagnosticSignHint",         { fg = c.primary })
hi("DiagnosticFloatingError",    { fg = c.error,     bg = c.container })
hi("DiagnosticFloatingWarn",     { fg = c.tertiary,  bg = c.container })

-- ===========================================================================
-- Syntax (classic vim highlight groups — treesitter below overrides these)
-- ===========================================================================
hi("Comment",       { fg = c.fg_muted, italic = true })
hi("Keyword",       { fg = c.primary,  bold = true })
hi("Statement",     { fg = c.primary })
hi("Conditional",   { fg = c.primary,  bold = true })
hi("Repeat",        { fg = c.primary,  bold = true })
hi("Function",      { fg = c.tertiary })
hi("Identifier",    { fg = c.fg })
hi("Type",          { fg = c.secondary })
hi("String",        { fg = c.secondary })
hi("Number",        { fg = c.tertiary })
hi("Float",         { fg = c.tertiary })
hi("Boolean",       { fg = c.primary })
hi("Operator",      { fg = c.fg })
hi("Delimiter",     { fg = c.outline })
hi("Special",       { fg = c.tertiary })
hi("SpecialChar",   { fg = c.primary })
hi("PreProc",       { fg = c.secondary })
hi("Include",       { fg = c.secondary })
hi("Define",        { fg = c.primary })
hi("Macro",         { fg = c.secondary })
hi("Constant",      { fg = c.tertiary })
hi("Tag",           { fg = c.primary })
hi("Title",         { fg = c.primary, bold = true })
hi("Bold",          { bold = true })
hi("Italic",        { italic = true })
hi("Underlined",    { underline = true })
hi("Todo",          { fg = c.primary, bold = true })
hi("Error",         { fg = c.error,   bold = true })

-- ===========================================================================
-- Treesitter (@-prefixed overrides vim syntax above)
-- ===========================================================================
hi("@comment",               { link = "Comment" })
hi("@comment.documentation", { fg = c.fg_muted, italic = true })

hi("@keyword",               { fg = c.primary, bold = true })
hi("@keyword.function",      { fg = c.primary, bold = true })
hi("@keyword.return",        { fg = c.primary })
hi("@keyword.operator",      { fg = c.primary })
hi("@keyword.import",        { fg = c.secondary })
hi("@keyword.coroutine",     { fg = c.primary })
hi("@keyword.conditional",   { fg = c.primary, bold = true })
hi("@keyword.repeat",        { fg = c.primary, bold = true })
hi("@keyword.exception",     { fg = c.error })

hi("@function",              { fg = c.tertiary })
hi("@function.builtin",      { fg = c.tertiary, italic = true })
hi("@function.call",         { fg = c.tertiary })
hi("@function.method",       { fg = c.tertiary })
hi("@function.method.call",  { fg = c.tertiary })
hi("@function.macro",        { fg = c.secondary })

hi("@variable",              { fg = c.fg })
hi("@variable.builtin",      { fg = c.primary, italic = true })
hi("@variable.parameter",    { fg = c.fg })
hi("@variable.member",       { fg = c.fg })

hi("@string",                { fg = c.secondary })
hi("@string.escape",         { fg = c.primary })
hi("@string.regex",          { fg = c.tertiary })
hi("@string.special",        { fg = c.primary })

hi("@number",                { fg = c.tertiary })
hi("@number.float",          { fg = c.tertiary })
hi("@boolean",               { fg = c.primary })

hi("@type",                  { fg = c.secondary })
hi("@type.builtin",          { fg = c.secondary, italic = true })
hi("@type.definition",       { fg = c.secondary })
hi("@type.qualifier",        { fg = c.primary })

hi("@attribute",             { fg = c.secondary })
hi("@namespace",             { fg = c.secondary })
hi("@module",                { fg = c.secondary })
hi("@module.builtin",        { fg = c.secondary, italic = true })

hi("@constructor",           { fg = c.secondary })
hi("@operator",              { fg = c.fg })
hi("@punctuation",           { fg = c.outline })
hi("@punctuation.bracket",   { fg = c.fg_muted })
hi("@punctuation.delimiter", { fg = c.outline })
hi("@punctuation.special",   { fg = c.primary })

hi("@property",              { fg = c.fg })
hi("@field",                 { fg = c.fg })
hi("@constant",              { fg = c.tertiary })
hi("@constant.builtin",      { fg = c.tertiary, italic = true })
hi("@constant.macro",        { fg = c.secondary })

hi("@label",                 { fg = c.primary })
hi("@exception",             { fg = c.error })

-- HTML / XML / JSX tags
hi("@tag",                   { fg = c.primary })
hi("@tag.attribute",         { fg = c.secondary })
hi("@tag.delimiter",         { fg = c.outline })

-- Markup
hi("@markup.heading",        { fg = c.primary, bold = true })
hi("@markup.link",           { fg = c.secondary, underline = true })
hi("@markup.link.url",       { fg = c.secondary, underline = true })
hi("@markup.link.label",     { fg = c.tertiary })
hi("@markup.italic",         { fg = c.fg, italic = true })
hi("@markup.bold",           { fg = c.fg, bold = true })
hi("@markup.raw",            { fg = c.tertiary })
hi("@markup.list",           { fg = c.primary })
hi("@markup.list.checked",   { fg = c.secondary })
hi("@markup.list.unchecked", { fg = c.fg_muted })

-- Diffs
hi("@diff.plus",             { fg = c.secondary })
hi("@diff.minus",            { fg = c.error })
hi("@diff.delta",            { fg = c.tertiary })

-- ===========================================================================
-- LSP semantic tokens
-- ===========================================================================
hi("@lsp.type.keyword",      { link = "@keyword" })
hi("@lsp.type.function",     { link = "@function" })
hi("@lsp.type.method",       { link = "@function.method" })
hi("@lsp.type.variable",     { link = "@variable" })
hi("@lsp.type.parameter",    { link = "@variable.parameter" })
hi("@lsp.type.type",         { link = "@type" })
hi("@lsp.type.class",        { link = "@type" })
hi("@lsp.type.interface",    { link = "@type" })
hi("@lsp.type.namespace",    { link = "@namespace" })
hi("@lsp.type.string",       { link = "@string" })
hi("@lsp.type.number",       { link = "@number" })
hi("@lsp.type.comment",      { link = "@comment" })
hi("@lsp.type.property",     { link = "@property" })
hi("@lsp.type.enum",         { link = "@type" })
hi("@lsp.type.enumMember",   { link = "@constant" })
hi("@lsp.type.struct",       { link = "@type" })
hi("@lsp.type.decorator",    { link = "@attribute" })
hi("@lsp.type.macro",        { link = "@function.macro" })
hi("@lsp.mod.deprecated",    { strikethrough = true })
hi("@lsp.mod.readonly",      { italic = true })

-- ===========================================================================
-- Git signs (gitsigns.nvim)
-- ===========================================================================
hi("GitSignsAdd",             { fg = c.secondary })
hi("GitSignsChange",          { fg = c.tertiary })
hi("GitSignsDelete",          { fg = c.error })
hi("GitSignsAddNr",           { fg = c.secondary })
hi("GitSignsChangeNr",        { fg = c.tertiary })
hi("GitSignsDeleteNr",        { fg = c.error })
hi("GitSignsAddLn",           { bg = c.cont_low })
hi("GitSignsChangeLn",        { bg = c.cont_low })
hi("GitSignsCurrentLineBlame",{ fg = c.outline, italic = true })

-- ===========================================================================
-- Neo-tree
-- ===========================================================================
hi("NeoTreeNormal",             { fg = c.fg,       bg = c.bg_dim })
hi("NeoTreeNormalNC",           { fg = c.fg_muted, bg = c.bg_dim })
hi("NeoTreeEndOfBuffer",        { fg = c.bg_dim,   bg = c.bg_dim })
hi("NeoTreeRootName",           { fg = c.primary,  bold = true })
hi("NeoTreeFileName",           { fg = c.fg })
hi("NeoTreeFileNameOpened",     { fg = c.primary })
hi("NeoTreeDirectoryName",      { fg = c.secondary })
hi("NeoTreeDirectoryIcon",      { fg = c.secondary })
hi("NeoTreeSymbolicLinkTarget", { fg = c.tertiary })
hi("NeoTreeGitAdded",           { fg = c.secondary })
hi("NeoTreeGitConflict",        { fg = c.error })
hi("NeoTreeGitDeleted",         { fg = c.error })
hi("NeoTreeGitIgnored",         { fg = c.outline })
hi("NeoTreeGitModified",        { fg = c.tertiary })
hi("NeoTreeGitUnstaged",        { fg = c.tertiary })
hi("NeoTreeGitUntracked",       { fg = c.primary })
hi("NeoTreeGitStaged",          { fg = c.secondary })
hi("NeoTreeIndentMarker",       { fg = c.outline_v })
hi("NeoTreeExpander",           { fg = c.outline })
hi("NeoTreeCursorLine",         { bg = c.container })
hi("NeoTreeDotfile",            { fg = c.fg_muted })
hi("NeoTreeHiddenByName",       { fg = c.outline })
hi("NeoTreeModified",           { fg = c.tertiary })
hi("NeoTreeMessage",            { fg = c.fg_muted, italic = true })
hi("NeoTreeTitleBar",           { fg = c.on_primary, bg = c.primary })
hi("NeoTreeFloatBorder",        { fg = c.outline, bg = c.container })
hi("NeoTreeFloatTitle",         { fg = c.primary, bold = true })

-- ===========================================================================
-- Telescope
-- ===========================================================================
hi("TelescopeNormal",          { fg = c.fg,        bg = c.container })
hi("TelescopePromptNormal",    { fg = c.fg,        bg = c.cont_high })
hi("TelescopePromptBorder",    { fg = c.cont_high, bg = c.cont_high })
hi("TelescopePromptTitle",     { fg = c.on_primary, bg = c.primary })
hi("TelescopeResultsNormal",   { fg = c.fg,        bg = c.container })
hi("TelescopeResultsBorder",   { fg = c.container, bg = c.container })
hi("TelescopeResultsTitle",    { fg = c.fg_muted })
hi("TelescopePreviewNormal",   { fg = c.fg,        bg = c.bg_dim })
hi("TelescopePreviewBorder",   { fg = c.bg_dim,    bg = c.bg_dim })
hi("TelescopePreviewTitle",    { fg = c.on_sec,    bg = c.secondary })
hi("TelescopeSelectionCaret",  { fg = c.primary })
hi("TelescopeSelection",       { bg = c.cont_high })
hi("TelescopeMatching",        { fg = c.primary, bold = true })
hi("TelescopeMultiSelection",  { fg = c.tertiary })

-- ===========================================================================
-- Which-key
-- ===========================================================================
hi("WhichKey",         { fg = c.primary })
hi("WhichKeyDesc",     { fg = c.fg })
hi("WhichKeyGroup",    { fg = c.secondary, bold = true })
hi("WhichKeySeparator",{ fg = c.outline })
hi("WhichKeyFloat",    { bg = c.container })
hi("WhichKeyBorder",   { fg = c.outline })
hi("WhichKeyValue",    { fg = c.fg_muted })

-- ===========================================================================
-- Noice
-- ===========================================================================
hi("NoicePopup",            { bg = c.container })
hi("NoicePopupBorder",      { fg = c.outline, bg = c.container })
hi("NoiceCmdline",          { bg = c.container })
hi("NoiceCmdlineIcon",      { fg = c.primary })
hi("NoiceCmdlineIconSearch",{ fg = c.secondary })
hi("NoiceCmdlinePopup",     { bg = c.container })
hi("NoiceCmdlinePopupBorder",{ fg = c.outline })
hi("NoiceConfirm",          { bg = c.container })
hi("NoiceConfirmBorder",    { fg = c.primary })
hi("NoiceMini",             { fg = c.fg_muted })

-- ===========================================================================
-- nvim-cmp
-- ===========================================================================
hi("CmpItemMenu",             { fg = c.fg_muted, italic = true })
hi("CmpItemAbbrDeprecated",   { fg = c.outline, strikethrough = true })
hi("CmpItemAbbrMatch",        { fg = c.primary, bold = true })
hi("CmpItemAbbrMatchFuzzy",   { fg = c.secondary, bold = true })
hi("CmpItemKindVariable",     { fg = c.fg })
hi("CmpItemKindInterface",    { fg = c.secondary })
hi("CmpItemKindText",         { fg = c.fg_muted })
hi("CmpItemKindFunction",     { fg = c.tertiary })
hi("CmpItemKindMethod",       { fg = c.tertiary })
hi("CmpItemKindKeyword",      { fg = c.primary })
hi("CmpItemKindSnippet",      { fg = c.primary })
hi("CmpItemKindField",        { fg = c.fg })
hi("CmpItemKindProperty",     { fg = c.fg })
hi("CmpItemKindEnum",         { fg = c.secondary })
hi("CmpItemKindUnit",         { fg = c.tertiary })
hi("CmpDocumentation",        { fg = c.fg, bg = c.container })
hi("CmpDocumentationBorder",  { fg = c.outline, bg = c.container })

-- ===========================================================================
-- Trouble
-- ===========================================================================
hi("TroubleNormal",       { fg = c.fg,       bg = c.bg_dim })
hi("TroubleNormalNC",     { fg = c.fg_muted, bg = c.bg_dim })
hi("TroubleText",         { fg = c.fg })
hi("TroubleCount",        { fg = c.primary,  bold = true })
hi("TroubleError",        { fg = c.error })
hi("TroubleWarning",      { fg = c.tertiary })
hi("TroubleHint",         { fg = c.primary })
hi("TroubleInformation",  { fg = c.secondary })

-- ===========================================================================
-- Todo Comments
-- ===========================================================================
hi("TodoBgTODO",    { fg = c.bg,  bg = c.primary   })
hi("TodoBgFIX",     { fg = c.bg,  bg = c.error     })
hi("TodoBgHACK",    { fg = c.bg,  bg = c.tertiary  })
hi("TodoBgNOTE",    { fg = c.bg,  bg = c.secondary })
hi("TodoBgWARN",    { fg = c.bg,  bg = c.tertiary  })
hi("TodoBgPERF",    { fg = c.bg,  bg = c.secondary })
hi("TodoBgTEST",    { fg = c.bg,  bg = c.primary   })
hi("TodoFgTODO",    { fg = c.primary   })
hi("TodoFgFIX",     { fg = c.error     })
hi("TodoFgHACK",    { fg = c.tertiary  })
hi("TodoFgNOTE",    { fg = c.secondary })
hi("TodoFgWARN",    { fg = c.tertiary  })
hi("TodoFgPERF",    { fg = c.secondary })
hi("TodoFgTEST",    { fg = c.primary   })
hi("TodoSignTODO",  { fg = c.primary   })
hi("TodoSignFIX",   { fg = c.error     })
hi("TodoSignHACK",  { fg = c.tertiary  })
hi("TodoSignNOTE",  { fg = c.secondary })

-- ===========================================================================
-- Indent Blankline (ibl)
-- ===========================================================================
hi("IblIndent",     { fg = c.outline_v })
hi("IblScope",      { fg = c.primary })
hi("IblWhitespace", { fg = c.outline_v })

-- ===========================================================================
-- Gitsigns diff highlights
-- ===========================================================================
hi("DiffAdd",       { fg = c.secondary, bg = "NONE" })
hi("DiffChange",    { fg = c.tertiary,  bg = "NONE" })
hi("DiffDelete",    { fg = c.error,     bg = "NONE" })
hi("DiffText",      { fg = c.fg,        bg = c.cont_high })
hi("diffAdded",     { fg = c.secondary })
hi("diffRemoved",   { fg = c.error })
hi("diffChanged",   { fg = c.tertiary })
hi("diffOldFile",   { fg = c.fg_muted })
hi("diffNewFile",   { fg = c.fg })
hi("diffFile",      { fg = c.primary })
hi("diffLine",      { fg = c.outline })

-- ===========================================================================
-- Flash.nvim
-- ===========================================================================
hi("FlashBackdrop", { fg = c.fg_muted })
hi("FlashMatch",    { fg = c.bg,     bg = c.secondary })
hi("FlashCurrent",  { fg = c.bg,     bg = c.primary, bold = true })
hi("FlashLabel",    { fg = c.bg,     bg = c.error, bold = true })
hi("FlashPrompt",   { fg = c.primary })

-- ===========================================================================
-- Dashboard
-- ===========================================================================
hi("DashboardHeader",      { fg = c.primary })
hi("DashboardCenter",      { fg = c.secondary })
hi("DashboardCenterIcon",  { fg = c.primary })
hi("DashboardShortCut",    { fg = c.tertiary })
hi("DashboardFooter",      { fg = c.fg_muted, italic = true })

-- ===========================================================================
-- Scrollbar
-- ===========================================================================
hi("ScrollbarHandle",       { bg = c.cont_high })
hi("ScrollbarCursor",       { fg = c.primary })
hi("ScrollbarCursorHandle", { fg = c.primary, bg = c.cont_high })
hi("ScrollbarError",        { fg = c.error })
hi("ScrollbarWarn",         { fg = c.tertiary })
hi("ScrollbarInfo",         { fg = c.secondary })
hi("ScrollbarHint",         { fg = c.primary })
hi("ScrollbarGitAdd",       { fg = c.secondary })
hi("ScrollbarGitChange",    { fg = c.tertiary })
hi("ScrollbarGitDelete",    { fg = c.error })

-- ===========================================================================
-- Fidget (LSP progress)
-- ===========================================================================
hi("FidgetTitle",  { fg = c.primary, bold = true })
hi("FidgetTask",   { fg = c.fg_muted })

-- ===========================================================================
-- Claude Code (claudecode.nvim)
-- ===========================================================================
hi("ClaudeCodeNormal", { fg = c.fg, bg = c.bg_dim })
hi("ClaudeCodeBorder", { fg = c.outline })
