# ===========================================================================
# modules/development/ai-tools/opencode/default.nix — OpenCode AI agent
#
# OpenCode is a terminal-native AI coding agent with TUI. It integrates with
# Neovim via opencode-nvim and VSCodium via the OpenCode extension.
#
# opencode-claude-auth: reuses Claude Code's existing OAuth credentials so
# you don't need a separate login for opencode.
#
# Dotfiles managed here:
#   tui.json      — TUI theme (colors regenerated by matugen on wallpaper change)
#   opencode.json — settings symlinked from ~/.agents/OpenCode/settings.json
#                   (synced via Syncthing across all linuxury hosts)
#
# Requires: modules/development/ai-tools/default.nix (nix-ld)
# ===========================================================================

{ pkgs, ... }:

{
  # =========================================================================
  # OpenCode — system-wide binaries (available to all users on this host)
  # =========================================================================
  environment.systemPackages = with pkgs; [
    opencode              # AI terminal agent — TUI + tool use + multi-model
    opencode-claude-auth  # reuses Claude Code OAuth creds in opencode
  ];

  # =========================================================================
  # Home Manager — dotfiles injected into every user on this host
  # =========================================================================
  home-manager.sharedModules = [
    ({ config, ... }: {
      home.file = {
        # TUI color theme — matugen regenerates this on every wallpaper change
        # force = true: matugen writes here; HM must not block with a collision
        ".config/opencode/tui.json" = {
          source = ../../../../dotfiles/opencode/tui.json;
          force  = true;
        };

        # Settings — live symlink to Syncthing-managed file in ~/.agents/OpenCode/
        # Any change made in the app persists and syncs across hosts automatically
        # Creates a dangling symlink for users without ~/.agents/OpenCode/ (harmless)
        ".config/opencode/opencode.json".source =
          config.lib.file.mkOutOfStoreSymlink
            "${config.home.homeDirectory}/.agents/OpenCode/settings.json";
      };
    })
  ];
}
